databases:
  - name: agronet-db
    databaseName: agronet
    user: agronet_user
    plan: free

services:
  - type: web
    name: agronet-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agronet-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
