# Generated by Django 6.0.3 on 2026-03-09 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('crop_type', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('tonnes', 'Tonnes'), ('bags', 'Bags'), ('crates', 'Crates'), ('pieces', 'Pieces')], default='kg', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(help_text='The farmer who owns this listing.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['crop_type', 'location'], name='idx_crop_location')],
            },
        ),
    ]
